trigger:
- master

pool: linuxpool 

stages:
- stage: build
  displayName: build stage
  pool: linuxpool
  jobs:
    - job: buildjob
      displayName: build job
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.12'
            addToPath: true
            architecture: 'x64'
            
        - script: |
            make venv
            source ~/.udacity-devops/bin/activate
            make install
          workingDirectory: .
          displayName: Create and start virtual environment Install dependencies
        
          

         
         

      

