trigger:
- master

pool: linuxpool

variables:
  projectRoot: $(System.DefaultWorkingDirectory)
  EnvironmentName: appenv_production
  WebAppName: mlapps-houseprice
  azureServiceConnectionId: 'azurerm-connection'
  #pythonVersion: '3.10'

stages:
- stage: build
  displayName: build stage
  pool: linuxpool
  jobs:
    - job: BuildJob
      displayName: BuildJob
      steps:
        - task: Cache@2
          inputs:
            key: 'pip | "$(Agent.OS)" | requirements.txt'
            restoreKeys: |
              pip | "$(Agent.OS)"
            path: ~/.cache/pip

        - script: |
            python3 --version
            make venv
            source ~/.udacity-devops/bin/activate
            make all
          workingDirectory: $(projectRoot)
          displayName: Install dependencies
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(projectRoot)'
            includeRootFolder: true
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true

- stage: deploy
  displayName: deploy web app to azure app service
  pool: linuxpool
  dependsOn: build
  condition: succeeded()
  jobs:
   - deployment: DeploymentJob
     environment: $(EnvironmentName)
     strategy:
        runOnce:
          deploy:
            steps:
            - task: AzureWebApp@1
              displayName: 'Deploy to Azure Web App'
              inputs:
                azureSubscription: $(azureServiceConnectionId)
                appType: 'webAppLinux'
                appName: $(webAppName)
                package: '$(projectRoot)/**/*.zip'
              
    

