trigger:
- master

pool: linuxpool 

stages:
- stage: build
  displayName: build stage
  pool: linuxpool
  jobs:
    - job: buildjob
      displayName: build job
      steps:
        - script: |
            python3 --version
            make venv
            source ~/.udacity-devops/bin/activate
            make install
          workingDirectory: .
          displayName: Create and start virtual environment Install dependencies
        
          

         
         

      

