name: Python application test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.18
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.18
    - name: Install dependencies
      run: |
        cd dev_ci
        make install
    - name: Lint with pylint
      run: |
        cd dev_ci
        make lint
    - name: Test with pytest
      run: |
        cd dev_ci
        make test
